title: Imperial Robotics
description: FTC Team 3734
author: Imperial Robotics
logo: /static/img/avatar.png
github: https://github.com/ImperialRobotics
about: Dallas, TX FTC team

baseurl: ""
url: "http://imperialrobotics.github.io"

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
